"""QMIX Mixer network — hypernetwork-based monotonic value factorization."""

from __future__ import annotations

import torch
import torch.nn as nn


class QMixer(nn.Module):
    """QMIX mixing network.

    Takes individual agent Q-values and mixes them into a global Q_tot
    while enforcing monotonicity (dQ_tot/dQ_i >= 0).

    The mixing weights are generated by hypernetworks conditioned on global state.
    """

    def __init__(self, n_agents: int, state_dim: int, hidden_dim: int = 32):
        super().__init__()
        self.n_agents = n_agents

        # Hypernetwork for first layer weights and biases
        # W1: (n_agents, hidden_dim), b1: (hidden_dim,)
        self.hyper_w1 = nn.Sequential(
            nn.Linear(state_dim, hidden_dim * 2),
            nn.ReLU(),
            nn.Linear(hidden_dim * 2, n_agents * hidden_dim),
        )
        self.hyper_b1 = nn.Linear(state_dim, hidden_dim)

        # Hypernetwork for second layer
        # W2: (hidden_dim, 1), b2: (1,)
        self.hyper_w2 = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.hyper_b2 = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1),
        )

        self.hidden_dim = hidden_dim

    def forward(self, q_values: torch.Tensor, states: torch.Tensor) -> torch.Tensor:
        """Mix individual Q-values into Q_tot.

        Args:
            q_values: (batch, n_agents) individual Q-values
            states: (batch, state_dim) global state

        Returns:
            q_tot: (batch, 1) total Q-value
        """
        batch_size = q_values.size(0)

        # First layer
        w1 = torch.abs(self.hyper_w1(states))  # (batch, n_agents * hidden_dim)
        w1 = w1.view(batch_size, self.n_agents, self.hidden_dim)  # (batch, n_agents, hidden)
        b1 = self.hyper_b1(states)  # (batch, hidden_dim)

        # q_values: (batch, n_agents) -> (batch, n_agents, 1)
        hidden = torch.bmm(q_values.unsqueeze(1), w1).squeeze(1)  # (batch, hidden_dim)
        hidden = torch.relu(hidden + b1)

        # Second layer
        w2 = torch.abs(self.hyper_w2(states))  # (batch, hidden_dim)
        w2 = w2.view(batch_size, self.hidden_dim, 1)  # (batch, hidden, 1)
        b2 = self.hyper_b2(states)  # (batch, 1)

        q_tot = torch.bmm(hidden.unsqueeze(1), w2).squeeze(1) + b2  # (batch, 1)

        return q_tot
